version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "200k"
    max-file: "10"
  driver: json-file


networks:
  default:
    driver: bridge


volumes:
  mysql-data:
    driver_opts:
      type: none
      device: ${STORAGE_DIR}/data/mysql
      o: bind

services:
  mysql:
    container_name: domainmod-mysql
    image: mariadb:10.3
    command: mysqld --sql_mode=""
    networks:
      - default
    restart: always
    logging: *default-logging
    environment:
      MYSQL_DATABASE: "domainmod"
      MYSQL_USER: "domainmod"
      MYSQL_PASSWORD: "domainmod"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
  domainmod:
    container_name: domainmod
    image: registry.ctrlzr.com/koshatul/domainmod:dev
    build: .
    networks:
      - default
    ports:
      - "8088:80/tcp"
    restart: always
    logging: *default-logging
